# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4
      # 使用云开发 Github Action 部署
      - name: Tencent CloudBase Github Action
        id: deployStatic
        # You may pin to the exact commit or the version.
        # uses: TencentCloudBase/cloudbase-action@a6f4e1491453f02f05f0df92337d4999a4e51c18
        # uses: TencentCloudBase/cloudbase-action@v2
        # uses: TencentCloudBase/cloudbase-action@98ad8f31eb7bc09a8da3699149a9f765c7d8e8a1
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          # 云开发 secretId
          secretId: ${{ secrets.SECRET_ID }}
          # 云开发 secretKey
          secretKey: ${{ secrets.SECRET_KEY }}
          # 云开发环境 Id
          envId: ${{ secrets.ENV_ID  }}
          # Github 项目静态文件的路径
          staticSrcPath: ./
          staticDestPath: ./side3
